CREATE TABLE `demo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  `message` VARCHAR(100) DEFAULT NULL COMMENT '信息内容',
  `status` INT(4) DEFAULT 0 COMMENT '状态',
  `isDelete` BOOL NOT NULL DEFAULT FALSE COMMENT '是否删除',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;
